/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: [".*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    "mdx-bundler",
    /^@apollo\/client.*/,
    /^@fal-works.*/,
    /^@javier.alejandro.castro\/react-mde.*/,
    /^@mdx-js.*/,
    /^astring.*/,
    /^bail.*/,
    /^ccount.*/,
    /^character-entities-html4.*/,
    /^character-entities-legacy.*/,
    /^character-entities.*/,
    /^character-reference-invalid.*/,
    /^comma-separated-tokens.*/,
    /^decode-named-character-reference.*/,
    /^estree-util.*/,
    /^fault.*/,
    /^hast-util.*/,
    /^hastscript.*/,
    /^is-.*/,
    /^mdast-util.*/,
    /^mdx-bundler.*/,
    /^micromark-extension-mdxjs.*/,
    /^micromark.*/,
    /^parse-entities.*/,
    /^periscopic.*/,
    /^property-information.*/,
    /^refractor.*/,
    /^remark.*/,
    /^space-separated-tokens.*/,
    /^stringify-entities.*/,
    /^trough.*/,
    /^unified.*/,
    /^unist-builder.*/,
    /^unist-util.*/,
    /^vfile.*/,
    /^zen-observable-ts.*/,
    /^zwitch.*/
  ]
};
