/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: [".*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    "remark-gfm",
    /micromark.*/,
    /mdast.*/,
    "ccount",
    /unist.*/,
    "decode-named-character-reference",
    "character-entities",
    "markdown-table",
    "mdx-bundler",
    /^refractor.*/,
    "hast-util-to-string",
    "remark-parse",
    "remark-directive",
    "@mdx-js/esbuild",
    /^@mdx-js\/mdx.*/,
    "unified",
    "bail",
    "trough",
    "remark-mdx",
    /^estree-util-.*/,
    "remark-rehype",
    "periscopic",
    "astring",
    "is-reference",
    "remark-frontmatter",
    "parse-entities",
    "stringify-entities",
    "character-entities-legacy",
    "character-reference-invalid",
    "is-decimal",
    "is-hexadecimal",
    "is-alphanumerical",
    "fault",
    "vfile",
    "is-alphabetical",
    "character-entities-html4",
    "vfile-message",
    "hastscript",
    /^@fal-works.*/,
    "property-information",
    /^hast-util-.*/,
    "space-separated-tokens",
    "comma-separated-tokens",
    "zwitch"
  ]
};
